### PR TITLE
make cron less noisy, option for extra args to be passed to simp_le, update README.md

### PR DESCRIPTION
**Pull request by JasperWallace**
Hi,

Here are a few more small improvements, sorry about odd merge stuff, i did it the wrong way round or something...

### CODE REVIEW

**Comment by L-P** [comment]
Looks okay.

Can you split this in two commits and rebase it on top of master please?

**Comment by JasperWallace** [comment]
as two seperate pull requests?

**Comment by L-P** [comment]
Nope, two commits in the same PR.

**Comment by JasperWallace** [comment]
See pr: https://github.com/Boaterfly/ansible-role-simp_le/pull/7

**Pull request closed without merging**
